site:
  build: .
  ports :
   - "9080:80"
  volumes:
   - public/:/var/www/html/
  links:
   - database

php-myadmin:
  image: corbinu/docker-phpmyadmin
  ports:
   - "8080:80"
  environment:
   - MYSQL_USERNAME=epics
   - MYSQL_PASSWORD=password
  links:
   - database:mysql

database:
  image: mysql
  ports:
   - "3333:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=epics
   - MYSQL_USER=epics
   - MYSQL_PASSWORD=password
  volumes:
   - ./data:/var/lib/mysql
